services:
  vlc-telnet:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/386
        - linux/amd64
        - linux/arm/v7
        - linux/arm64
      cache_from:
        - ne1ver/vlc-telnet:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: vlc-telnet
    ports:
      - "4212:4212"
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      VLC_TELNET_PASSWORD: ${VLC_TELNET_PASSWORD}
      ALSA_DEVICE: ${ALSA_DEVICE:-USB Audio}
    restart: unless-stopped
